# -*- coding: utf-8 -*-
"""Emotions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSZZLcTr4YI2hLT8zdF1hiewCOtkquo9
"""

import streamlit as st
import joblib

# Load the trained SVC model
model = joblib.load("svc_model(2).pkl")  # Ensure this file is in the same directory

# Optional: load label encoder or emotion map
label_to_emotion = {0: "Happy", 1: "Sad", 2: "Angry", 3: "Fear", 4: "Neutral"}

# Title
st.title("🎭 Emotion Classifier")
st.subheader("Predict emotion from text using SVC")

# Input text box
user_input = st.text_area("Enter your sentence:", "I am feeling awesome today!")

# Predict button
if st.button("Predict Emotion"):
    if user_input.strip() == "":
        st.warning("Please enter some text!")
    else:
        # Vectorize your input (assuming you used TF-IDF or CountVectorizer)
        vectorizer = joblib.load("vectorizer.pkl")  # Ensure it's saved and uploaded too
        input_vector = vectorizer.transform([user_input])

        # Make prediction
        prediction = model.predict(input_vector)[0]
        emotion = label_to_emotion.get(prediction, "Unknown")

        st.success(f"Predicted Emotion: **{emotion}**")
